id: I944AB143
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.126853
last_modified: 2023-02-09 14:46:46.126952
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  25B5:
    base_file: 25B5.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
